version: '3.8'

services:
  mcpay-api:
    build: .
    ports:
      - "${SERVER_PORT:-8002}:8002"
    env_file:
      - .env              # 加载基础配置
      - .env.docker       # 加载Docker环境覆盖配置
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: