server:
  debug: true
  name: api
  port: 8002
database:
  mysql:
    DSN: root:1122334@tcp(127.0.0.1:3308)/mcpay?charset=utf8mb4&timeout=10s&parseTime=true&loc=Local
    max_open_connections: 100
    max_idle_connections: 25
    max_life_seconds: 5*60
  mongo:
#    host: 165.154.215.88:27020
    host: 38.60.199.53:27020
    user: root
#    pwd: fdas23fdew
    pwd: dffhu322
payment:
  callback: https://wapi.hipoker.xyz/callback

